spring:
  # dev|test|prod
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000ms
    expire: 10
  application:
    name: service-consumer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
server:
  port: 8090